// Generated by gencpp from file cyber_msgs/GimbalCommand.msg
// DO NOT EDIT!


#ifndef CYBER_MSGS_MESSAGE_GIMBALCOMMAND_H
#define CYBER_MSGS_MESSAGE_GIMBALCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cyber_msgs
{
template <class ContainerAllocator>
struct GimbalCommand_
{
  typedef GimbalCommand_<ContainerAllocator> Type;

  GimbalCommand_()
    : header()
    , cmd(0)
    , data(0.0)  {
    }
  GimbalCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cmd(0)
    , data(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _cmd_type;
  _cmd_type cmd;

   typedef double _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cyber_msgs::GimbalCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyber_msgs::GimbalCommand_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalCommand_

typedef ::cyber_msgs::GimbalCommand_<std::allocator<void> > GimbalCommand;

typedef boost::shared_ptr< ::cyber_msgs::GimbalCommand > GimbalCommandPtr;
typedef boost::shared_ptr< ::cyber_msgs::GimbalCommand const> GimbalCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyber_msgs::GimbalCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cyber_msgs::GimbalCommand_<ContainerAllocator1> & lhs, const ::cyber_msgs::GimbalCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cmd == rhs.cmd &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cyber_msgs::GimbalCommand_<ContainerAllocator1> & lhs, const ::cyber_msgs::GimbalCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cyber_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyber_msgs::GimbalCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyber_msgs::GimbalCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyber_msgs::GimbalCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "471da938d569c4b9e4e848a057da3c1d";
  }

  static const char* value(const ::cyber_msgs::GimbalCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x471da938d569c4b9ULL;
  static const uint64_t static_value2 = 0xe4e848a057da3c1dULL;
};

template<class ContainerAllocator>
struct DataType< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyber_msgs/GimbalCommand";
  }

  static const char* value(const ::cyber_msgs::GimbalCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint8 cmd\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cyber_msgs::GimbalCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cmd);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyber_msgs::GimbalCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyber_msgs::GimbalCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBER_MSGS_MESSAGE_GIMBALCOMMAND_H
